name: trigger
run-name: trigger-${{ github.run_id }}

on:
  workflow_call:
    inputs:
      workflow-ref:
        description: The reference of the workflow to trigger (tag or branch).
        required: true
        type: string
      workflow-path:
        description: The path to the execute workflow file.
        required: true
        type: string
      build-version:
        description: The version to be used.
        required: false
        default: ''
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow
        uses: lordlive/custom-action/trigger@v1.0.7
        with:
          workflow-ref: ${{ inputs.workflow-ref }}
          workflow-path: ${{ inputs.workflow-path }}
          build-version: ${{ inputs.build-version }}
